### ISSUE TITLE
YouTube -- Advanced Feature Verification

### ISSUE THREAD

**Issue by maggiespear** [jspear16/GBC-Website#12]
We have verified the YouTube channel mostly, however, there are a few more things that need to be done. They are:

- Video verification
- Valid ID

These need to be done in order to fully unlock the "Advanced Features". While the "Advanced Features" say it is enabled, when you go to the drop down beside it, the aforementioned items are not yet completed. We should go ahead and do these as I don't want to run into an issue with this later. I believe there are some livestream capabilities that are not allowed, but I can't fully remember.

**Comment by jspear16** [comment]
While it says it is "enabled" the aforementioned things still should be done for completeness.

**Comment by jspear16** [comment]
It appears that this is still good enough to qualify the channel for Advanced Features so I am closing the issue.
